apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-render
  name: image-render
  namespace: monitoring
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: image-render
  type: ClusterIP